swagger: "2.0"
info:
  description: "An API used to query information about datasets published by the ONS."
  version: "1.0.0"
  title: "ONS Dataset API"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
tags:
- name: "Dataset"
schemes:
- "http"
parameters:
  id:
    name: id
    description: "Id that represents a dataset type"
    in: path
    type: string
    required: true
  edition:
    name: edition
    description: "An edition of a dataset"
    in: path
    type: string
    required: true
  version:
    name: version
    description: "A version of a dataset dataset"
    in: path
    type: string
    required: true
  dimension:
    name: dimension
    description: "A dimension from a dataset"
    in: path
    type: string
    required: true
  offset:
    name: offset
    description: "The offset from the start of results. This defaults to 0"
    in: query
    type: integer
  limit:
    name: limit
    description: "Limit the number of results returned. This defaults to 20"
    in: query
    type: integer
  query:
    name: q
    description: "The query text to search datasets with"
    in: query
    type: string
paths:
  /search/datasets:
    get:
      tags:
      - "Dataset"
      summary: "Search for datasets"
      description: "Perform a search on all published datasets by the ONS"
      parameters:
      - $ref: '#/parameters/query'
      - $ref: '#/parameters/offset'
      - $ref: '#/parameters/limit'
      produces:
      - "application/json"
      responses:
        200:
          description: "A json list contain datasets which have been published"
          schema:
            $ref: '#/definitions/Datasets'
        400:
          description: "Body of the post request is invalid"
        500:
          description: "Failed to process the request due to a internal error"
  /datasets:
    get:
      tags:
      - "Dataset"
      summary: "Get a list of datasets"
      description: "Returns a list of all datasets provided by the ONS that can be filtered using the filter API"
      parameters:
      - $ref: '#/parameters/offset'
      - $ref: '#/parameters/limit'
      produces:
      - "application/json"
      responses:
        200:
          description: "A json list contain datasets which have been published"
          schema:
            $ref: '#/definitions/Datasets'
        500:
          description: "Failed to process the request due to a internal error"

  /datasets/{id}:
    get:
      tags:
      - "Dataset"
      summary: "Get a dataset"
      description: "The dataset contains the name of it and a link to all editions"
      parameters:
      - $ref: '#/parameters/id'
      responses:
        200:
          description: "A json object for a single Dataset"
          schema:
            $ref: '#/definitions/Dataset'
        404:
          description: "No dataset was found using the id provided"
        500:
          description: "Failed to process the request due to a internal error"
  /datasets/{id}/editions:
    get:
      tags:
      - "Dataset"
      summary: "Get a list of all editions from a dataset"
      description: "Get a list of editions from a type of dataset"
      parameters:
      - $ref: '#/parameters/id'
      responses:
        200:
          description: "A json list contain all editions for a dataset"
          schema:
            $ref: '#/definitions/Editions'
        404:
          description: "No dataset was found using the id provided"
        500:
          description: "Failed to process the request due to a internal error"
  /datasets/{id}/editions/{edition}:
    get:
      tags:
      - "Dataset"
      summary: "Get a edition of a dataset"
      description: "The edition contains a link to all versions"
      parameters:
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/edition'
      responses:
        200:
          description: "A json object containing an edition"
          schema:
            $ref: '#/definitions/Edition'
        404:
          description: "No dataset edition was found using the id and edition provided"
        500:
          description: "Failed to process the request due to a internal error"
  /datasets/{id}/editions/{edition}/versions:
    get:
      tags:
      - "Dataset"
      summary: "Get a list of all versions from a dataset edition"
      description: "Get a list of all versions from a dataset edition"
      parameters:
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/edition'
      responses:
        200:
          description: "A json list containing all version for a set type of dataset and edition"
          schema:
            $ref: '#/definitions/Versions'
        404:
          description: "No dataset edition was found using the id and edition provided"
        500:
          description: "Failed to process the request due to a internal error"
  /datasets/{id}/editions/{edition}/versions/{version}:
    get:
      tags:
      - "Dataset"
      summary: "Get a specific version and edition of a dataset"
      description: "Get a specific version and edition of a dataset"
      parameters:
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/version'
      responses:
        200:
          description: "A json object containing the edition and version of a dataset"
          schema:
            $ref: '#/definitions/DatasetDetails'
        404:
          description: "No dataset edition with the specific version was found using the id, edition and version provided"
        500:
          description: "Failed to process the request due to a internal error"
  /datasets/{id}/editions/{edition}/versions/{version}/dimensions:
    get:
      tags:
      - "Dataset"
      summary: "Get all dimensions from a dataset"
      description: "Get all dimensions which are used in the dataset"
      parameters:
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/version'
      - $ref: '#/parameters/offset'
      - $ref: '#/parameters/limit'
      responses:
        200:
          description: "A json list of dimensions"
          schema:
            $ref: '#/definitions/Dimensions'
        404:
          description: "No dataset edition with the specific version was found using the id, edition and version provided"
        500:
          description: "Failed to process the request due to a internal error"
  /datasets/{id}/editions/{edition}/versions/{version}/dimensions/{dimension}:
    get:
      tags:
      - "Dataset"
      summary: "Get all values from a dimension"
      description: "Get a list of all values which appear in this dimension and dataset"
      parameters:
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/version'
      - $ref: '#/parameters/dimension'
      responses:
        200:
          description: "Json object containing all values for a dimension"
          schema:
            $ref: '#/definitions/DimensionValues'
        404:
          description: "No dataset edition with the specific version was found using the id, edition and version provided or the dimension does not exist within the dataset"
        500:
          description: "Failed to process the request due to a internal error"
definitions:
  Dataset:
    type: object
    properties:
      id:
        type: string
        description: "An unique id for a dataset"
        example: "DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC"
      name:
        type: string
        description: "The name of the dataset"
        example: "CPI"
      editions_url:
        type: string
        description: "A URL to all editions for a dataset"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC/editions"
  Datasets:
    type: object
    properties:
      items:
        type: array
        description: "A list of datasets"
        items:
          $ref: '#/definitions/Dataset'
  Edition:
    type: object
    properties:
      id:
        type: string
        description: "An unique id for a dataset"
        example: "DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC"
      name:
        type: string
        description: "The name of the dataset"
        example: "CPI"
      edition:
        type: string
        description: "The dataset edtion"
        example: "2017"
      versions_url:
        type: string
        description: "A URL to all versions for this dataset edition"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC/editions/2017/versions"
  Editions:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Edition'
  Versions:
    type: object
    properties:
      items:
        type: array
        description: "An array of Datasets"
        items:
          type: object
          properties:
            id:
              type: string
              description: "An unique id for a dataset"
              example: "DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC"
            name:
              type: string
              description: "The name of the dataset"
              example: "CPI"
            edition:
              type: string
              description: "The edition of the dataset"
              example: "2017"
            version:
               type: integer
               description: "The version of a dataset edition"
               example: "3"
            dataset_url:
              type: string
              description: "A URL to a full description of the dataset"
              example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC/editions/2017/versions/3"
  DatasetDetails:
    type: object
    description: "An object containing information about published datasets from the ONS"
    properties:
      id:
        type: integer
        description: "The dataset id"
      title:
        type: string
        description: "The title for the dataset"
      release_date:
        type: string
        description: "The release date of this dataset"
      next_release:
        type: string
        description: "The next release date for this dataset"
      edition:
        type: string
        description: "The edition of the dataset"
      version:
        type: string
        description: "The version of the dataset"
      dimensions:
        type: string
        description: "A link to all dimensions within this dataset"
      contact:
        type: object
        description: "Object containing contact information for this dataset"
        properties:
          name:
            type: string
            description: "The name of the person"
          telephone:
            type: string
            description: "Telephone number to contact the person"
          email:
            type: string
            description: "An email address to contact the person"
  Dimension:
    type: object
    description: "A single dimension within a dataset"
    properties:
      codeListId:
        type: string
        description: "The id of the code list that refers to this dimension"
      id:
        type: string
        description: "The id of the dimension"
      name:
        type: string
        description: "The name of the dimension"
      type:
        type: string
        description: "The type of dimension"
  Dimensions:
    type: object
    properties:
      items:
        type: array
        description: "An array of dimensions"
        items:
          $ref: '#/definitions/Dimension'
      number_of_results:
              type: integer
              description: "The number of results available"
  DimensionValues:
    type: object
    properties:
      code_list_id:
        type: string
        description: "The id of the code list that refers to this dimension"
      id:
        type: string
        description: "The id of the dimension"
      name:
        type: string
        description: "The name of the dimension"
      type:
        type: string
        description: "The type of dimension"
      values:
        type: array
        description: "A list of values within a dimension"
        items:
          type: string