swagger: "2.0"
info:
  description: "An API used to query information about datasets published by the ONS."
  version: "1.0.0"
  title: "Dataset API"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
tags:
- name: "Public API"
- name: "Private user API"
- name: "Private"
schemes:
- "http"
parameters:
  dimension:
    name: dimension
    description: "A dimension from a dataset"
    in: path
    required: true
    type: string
  edition:
    name: edition
    description: "An edition of a dataset"
    in: path
    required: true
    type: string
  id:
    name: id
    description: "Id that represents a dataset type"
    in: path
    required: true
    type: string
  items_per_page:
    name: items_per_page
    description: "The number of datasets to be returned"
    in: query
    type: integer
  new_dataset:
    name: dataset
    description: "A new dataset"
    in: body
    required: true
    schema:
      $ref: '#/definitions/Dataset'
  new_edition:
    name: new_edition
    description: "A new edition of the dataset"
    in: body
    required: true
    schema:
      $ref: '#/definitions/Edition'
  new_version:
    name: new_version
    description: "A new version of the dataset edition"
    in: body
    required: true
    schema:
      $ref: '#/definitions/Version'
  query:
    name: q
    description: "The query text to search datasets with"
    in: query
    type: string
  start_index:
    name: start_index
    description: "The first row of datasets to retrieve, starting at 0. Use this parameter as a pagination mechanism along with the items_per_page parameter"
    in: query
    type: integer
  version:
    name: version
    description: "A version of a dataset"
    in: path
    required: true
    type: string
paths:
  /search/datasets:
    get:
      tags:
      - "Public API"
      summary: "Search for datasets"
      description: "Perform a search on all published datasets by the ONS"
      parameters:
      - $ref: '#/parameters/items_per_page'
      - $ref: '#/parameters/query'
      - $ref: '#/parameters/start_index'
      produces:
      - "application/json"
      responses:
        200:
          description: "A json list containing datasets which have been published"
          schema:
            $ref: '#/definitions/Datasets'
        400:
          description: "Body of the post request is invalid"
        500:
          description: "Failed to process the request due to an internal error"
  /datasets:
    post:
      tags:
      - "Private user API"
      summary: "Create a dataset"
      description: "Create a dataset provided by the ONS that can be filtered using the filter API"
      parameters:
      - $ref: '#/parameters/new_dataset'
      produces:
      - "application/json"
      responses:
        200:
          description: "A json list containing datasets which have been published"
        400:
          description: "Invalid request body"
        500:
          $ref: '#/responses/InternalError'
    get:
      tags:
      - "Public API"
      summary: "Get a list of datasets"
      description: "Returns a list of all datasets provided by the ONS that can be filtered using the filter API"
      produces:
      - "application/json"
      responses:
        200:
          description: "A json list containing datasets which have been published"
          schema:
            $ref: '#/definitions/Datasets'
        500:
          $ref: '#/responses/InternalError'
  /datasets/{id}:
    get:
      tags:
      - "Public API"
      summary: "Get a dataset"
      description: "The dataset contains all high level information, for additional details see editions or versions of a dataset"
      parameters:
      - $ref: '#/parameters/id'
      responses:
        200:
          description: "A json object for a single Dataset"
          schema:
            $ref: '#/definitions/Dataset'
        404:
          description: "No dataset was found using the id provided"
        500:
          $ref: '#/responses/InternalError'
  /datasets/{id}/editions:
    get:
      tags:
      - "Public API"
      summary: "Get a list of all editions from a dataset"
      description: "Get a list of editions from a type of dataset"
      parameters:
      - $ref: '#/parameters/id'
      responses:
        200:
          description: "A json list containing all editions for a dataset"
          schema:
            $ref: '#/definitions/Editions'
        404:
          description: "No dataset was found using the id provided"
        500:
          $ref: '#/responses/InternalError'
  /datasets/{id}/editions/{edition}:
    post:
      tags:
      - "Private user API"
      summary: "Create an edition of a dataset"
      description: "Create an edition of a dataset"
      parameters:
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/new_edition'
      responses:
        201:
          description: "A json object containing an edition"
        400:
          description: "Invalid request body"
        404:
          description: "No dataset was found using the id provided"
        500:
          $ref: '#/responses/InternalError'
    get:
      tags:
      - "Public API"
      summary: "Get an edition of a dataset"
      description: "The edition contains a link to all versions"
      parameters:
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/id'
      responses:
        200:
          description: "A json object containing an edition"
          schema:
            $ref: '#/definitions/Edition'
        404:
          description: "No dataset edition was found using the id and edition provided"
        500:
          $ref: '#/responses/InternalError'
  /datasets/{id}/editions/{edition}/versions:
    get:
      tags:
      - "Public API"
      summary: "Get a list of all versions from a dataset edition"
      description: "Get a list of all versions from a dataset edition"
      parameters:
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/id'
      responses:
        200:
          description: "A json list containing all versions for a set type of dataset and edition"
          schema:
            $ref: '#/definitions/Versions'
        404:
          description: "No dataset edition was found using the id and edition provided"
        500:
          $ref: '#/responses/InternalError'
  /datasets/{id}/editions/{edition}/versions/{version}:
    post:
      tags:
      - "Private user API"
      summary: "Create a version of a dataset edition"
      description: "Create a version of a dataset edition"
      parameters:
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/new_version'
      - $ref: '#/parameters/version'
      responses:
        201:
          description: "A json object containing a version"
        400:
          description: "Invalid request body"
        404:
          description: "No dataset edition was found using the id and edition provided"
        500:
          $ref: '#/responses/InternalError'
    get:
      tags:
      - "Public API"
      summary: "Get a specific version and edition of a dataset"
      description: "Get a specific version and edition of a dataset"
      parameters:
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/version'
      responses:
        200:
          description: "A json object containing the edition and version of a dataset"
          schema:
            $ref: '#/definitions/Version'
        404:
          description: "No dataset edition with the specific version was found using the id, edition and version provided"
        500:
          $ref: '#/responses/InternalError'
  /datasets/{id}/editions/{edition}/versions/{version}/dimensions:
    get:
      tags:
      - "Public API"
      summary: "Get all dimensions from a dataset"
      description: "Get all dimensions which are used in the dataset"
      parameters:
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/version'
      responses:
        200:
          description: "A json list of dimensions"
          schema:
            $ref: '#/definitions/Dimensions'
        404:
          description: "No dataset edition with the specific version was found using the id, edition and version provided"
        500:
          $ref: '#/responses/InternalError'
  /datasets/{id}/editions/{edition}/versions/{version}/dimensions/{dimension}:
    get:
      tags:
      - "Public API"
      summary: "Get all values from a dimension"
      description: "Get a list of all values which appear in this dimension and dataset"
      parameters:
      - $ref: '#/parameters/dimension'
      - $ref: '#/parameters/edition'
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/version'
      responses:
        200:
          description: "Json object containing all values for a dimension"
          schema:
            $ref: '#/definitions/DimensionValues'
        404:
          description: "No dataset edition with the specific version was found using the id, edition and version provided or the dimension does not exist within the dataset"
        500:
          $ref: '#/responses/InternalError'
responses:
  InternalError:
    description: "Failed to process the request due to an internal error"
definitions:
  Contact:
    description: "Object containing contact information for this dataset"
    type: object
    properties:
      email:
        description: "An email address to contact the person"
        type: string
      name:
        description: "The name of the person"
        type: string
      telephone:
        description: "Telephone number to contact the person"
        type: string
  Datasets:
    description: "A list of datasets"
    type: object
    properties:
      count:
        description: "The number of datasets returned"
        readOnly: true
        type: integer
      items:
        type: array
        items:
          $ref: '#/definitions/Dataset'
      items_per_page:
        description: "The number of datasets requested"
        type: integer
      start_index:
        description: "The first row of datasets to retrieve, starting at 0. Use this parameter as a pagination mechanism along with the items_per_page parameter"
        type: integer
      total_count:
        description: "The total number of datasets"
        readOnly: true
        type: integer
  Dataset:
    description: "The dataset"
    type: object
    properties:
      contact:
        type: array
        description: "Object containing contact information for this dataset"
        items:
          $ref: '#/definitions/Contact'
      description:
        type: string
        description: "A description for a dataset"
      _id:
        readOnly: true
        type: string
        description: "An unique id for a dataset"
        example: "DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC"
      links:
        $ref: '#/definitions/DatasetLinks'
      next_release:
        type: string
        description: "The next release date for this dataset"
      periodicity:
        type: string
        description: "The periodicity for a dataset"
      publisher:
        $ref: '#/definitions/Publisher'
      state:
        $ref: '#/definitions/State'
      theme:
        type: string
        description: "A theme for a dataset"
      title:
        type: string
        description: "The title of the dataset"
        example: "CPI"
      updated_at:
        readOnly: true
        type: string
        description: "The time and date in which the resource was last updated"
        example: "2017-10-23T15:09:11.829+01:00"
  DatasetLinks:
    description: "A list of links related to this resource"
    readOnly: true
    type: object
    properties:
      editions:
        description: "A URL to all editions for this dataset"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC/editions"
        type: string
      latest_version:
        description: "A link to the latest version and edition of the dataset"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC/editions/2017/versions/2"
        type: string
      self:
        $ref: '#/definitions/SelfLink'
  Edition:
    type: object
    properties:
      edition:
        description: "The edition of the dataset"
        example: "2017"
        type: string
      id:
        description: "An unique id for a dataset edtion"
        readOnly: true
        type: string
      links:
        $ref: '#/definitions/EditionLinks'
      state:
        $ref: '#/definitions/State'
  Editions:
    type: object
    properties:
      count:
        description: "The number of editions returned for a dataset"
        readOnly: true
        type: integer
      items:
        type: array
        items:
          $ref: '#/definitions/Edition'
      items_per_page:
        description: "The number of editions requested for a dataset"
        type: integer
      start_index:
        description: "The first row of editions for a dataset to retrieve, starting at 0. Use this parameter as a pagination mechanism along with the items_per_page parameter"
        type: integer
      total_count:
        description: "The total number of editions against a dataset"
        readOnly: true
        type: integer
  EditionLinks:
    readOnly: true
    type: object
    properties:
      dataset:
        description: "A URL to the editions parent dataset"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC"
        type: string
      self:
        $ref: '#/definitions/SelfLink'
      versions:
        description: "A URL to all versions of this dataset edition"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC/edition/2017/versions"
        type: string
  Publisher:
    description: "The publisher of the dataset"
    type: object
    properties:
      name:
        description: "The name of the publisher"
        type: string
      type:
        description: "The type of publisher"
        type: string
      url:
        description: "A link to the publishers homepage"
        type: string
  SelfLink:
    description: "A link to this resource"
    readOnly: true
    type: string
  State:
    description: |
      The state of the resource, can only be one of the following:
        * created
        * associated
        * published
    type: string
  Versions:
    type: object
    properties:
      count:
        description: "The number of versions returned for a dataset edition"
        readOnly: true
        type: integer
      items:
        description: "An array of Datasets"
        type: array
        items:
          $ref: '#/definitions/Version'
      items_per_page:
        description: "The number of versions requested for a dataset edition"
        type: integer
      start_index:
        description: "The first row of versions for a dataset edition to retrieve, starting at 0. Use this parameter as a pagination mechanism along with the items_per_page parameter"
        type: integer
      total_count:
        description: "The total number of versions against a dataset edition"
        readOnly: true
        type: integer
  Version:
    description: "An object containing information about published datasets from the ONS"
    type: object
    properties:
      edition:
        description: "The dataset edition for this version"
        type: string
      license:
        description: "The type of license for the dataset"
        type: string
      links:
        $ref: '#/definitions/VersionLinks'
      release_date:
        description: "The release date of this dataset"
        type: string
      state:
        $ref: '#/definitions/State'
      version:
        description: "The number of the dataset edition version"
        type: integer
  VersionLinks:
    description: "A list of links related to this resource"
    readOnly: true
    type: object
    properties:
      dataset:
        $ref: '#/definitions/DatasetLink'
      dimensions:
        $ref: '#/definitions/DimensionLink'
      edition:
        $ref: '#/definitions/EditionLink'
      self:
        $ref: '#/definitions/SelfLink'
  DatasetLink:
    description: "An object containing the dataset id and link"
    readOnly: true
    type: object
    properties:
      id:
        description: "The dataset id"
        type: string
      link:
        description: "A URL to the dataset for this version"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC"
        type: string
  DimensionLink:
    description: "An object containing the dimension id and link"
    readOnly: true
    type: object
    properties:
      id:
        description: "The dimension id"
        type: string
      link:
        description: "A URL to list dimensions for this version"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC/editions/2017/versions/2/dimensions"
        type: string
  EditionLink:
    description: "An object containing the edition and link"
    readOnly: true
    type: object
    properties:
      id:
        description: "The version dataset edition"
        type: string
      link:
        description: "A URL to the dataset edition for this version"
        example: "http://localhost:8080/datasets/DE3BC0B6-D6C4-4E20-917E-95D7EA8C91DC/editions/2017"
        type: string
  Dimension:
    description: "A single dimension within a dataset"
    type: object
    properties:
      codeListId:
        description: "The id of the code list that refers to this dimension"
        type: string
      id:
        description: "The id of the dimension"
        type: string
      name:
        description: "The name of the dimension"
        type: string
      type:
        description: "The type of dimension"
        type: string
  Dimensions:
    type: object
    properties:
      count:
        description: "The number of dimensions returned for a version from a dataset edition"
        readOnly: true
        type: integer
      items:
        description: "An array of dimensions"
        type: array
        items:
          $ref: '#/definitions/Dimension'
      items_per_page:
        description: "The number of dimensions requested for a version from a dataset edition"
        type: integer
      start_index:
        description: "The first row of dimension for a version from a dataset edition to retrieve, starting at 0. Use this parameter as a pagination mechanism along with the items_per_page parameter"
        type: integer
      total_count:
        description: "The total number of dimensions against a version from a dataset edition"
        readOnly: true
        type: integer
  DimensionValues:
    type: object
    properties:
      code_list_id:
        description: "The id of the code list that refers to this dimension"
        type: string
      id:
        description: "The id of the dimension"
        type: string
      name:
        description: "The name of the dimension"
        type: string
      type:
        description: "The type of dimension"
        type: string
      values:
        description: "A list of values within a dimension"
        type: array
        items:
          type: string
